import { Archive, BarChart3, BellRing, Bus, Car, CalendarDays, FileText, GitBranch, LayoutDashboard, MapPinned, Route, ScrollText, Settings, ShieldCheck, UserCog, Users, Building2, Smartphone } from 'lucide-react';
import { Role } from '../types';

export const menuByRole: Record<Role, { to: string; label: string; icon: any }[]> = {
  SUPER_ADMIN: [
    { to: '/', label: 'Dashboard', icon: LayoutDashboard },
    { to: '/departments', label: 'Departments', icon: Building2 },
    { to: '/employees', label: 'Employees', icon: Users },
    { to: '/users', label: 'Users', icon: UserCog },
    { to: '/routes', label: 'Routes', icon: Route },
    { to: '/places', label: 'Places', icon: MapPinned },
    { to: '/vehicles', label: 'Vehicles', icon: Car },
    { to: '/drivers', label: 'Drivers', icon: Bus },
    { to: '/requests', label: 'Requests', icon: FileText },
    { to: '/approvals', label: 'Approvals', icon: ShieldCheck },
    { to: '/groups', label: 'Dispatch Board', icon: GitBranch },
    { to: '/grouping-templates', label: 'Grouping Templates', icon: GitBranch },
    { to: '/analytics', label: 'Analytics', icon: BarChart3 },
    { to: '/reports', label: 'Reports', icon: FileText },
    { to: '/holidays', label: 'Holidays', icon: CalendarDays },
    { to: '/archive', label: 'Archive', icon: Archive },
    { to: '/audit-logs', label: 'Audit Logs', icon: ScrollText },
    { to: '/settings', label: 'Settings', icon: Settings },
    { to: '/profile', label: 'Profile', icon: UserCog },
  ],
  ADMIN: [
    { to: '/', label: 'Dashboard', icon: LayoutDashboard },
    { to: '/departments', label: 'Departments', icon: Building2 },
    { to: '/employees', label: 'Employees', icon: Users },
    { to: '/users', label: 'Users', icon: UserCog },
    { to: '/routes', label: 'Routes', icon: Route },
    { to: '/places', label: 'Places', icon: MapPinned },
    { to: '/vehicles', label: 'Vehicles', icon: Car },
    { to: '/drivers', label: 'Drivers', icon: Bus },
    { to: '/requests', label: 'Requests', icon: FileText },
    { to: '/approvals', label: 'Approvals', icon: ShieldCheck },
    { to: '/groups', label: 'Dispatch Board', icon: GitBranch },
    { to: '/grouping-templates', label: 'Grouping Templates', icon: GitBranch },
    { to: '/analytics', label: 'Analytics', icon: BarChart3 },
    { to: '/reports', label: 'Reports', icon: FileText },
    { to: '/holidays', label: 'Holidays', icon: CalendarDays },
    { to: '/archive', label: 'Archive', icon: Archive },
    { to: '/audit-logs', label: 'Audit Logs', icon: ScrollText },
    { to: '/settings', label: 'Settings', icon: Settings },
    { to: '/profile', label: 'Profile', icon: UserCog },
  ],
  HOD: [
    { to: '/', label: 'Dashboard', icon: LayoutDashboard },
    { to: '/employees', label: 'Employees', icon: Users },
    { to: '/users', label: 'Users', icon: UserCog },
    { to: '/places', label: 'Places', icon: MapPinned },
    { to: '/requests', label: 'Requests', icon: FileText },
    { to: '/approvals', label: 'Approvals', icon: ShieldCheck },
    { to: '/groups', label: 'Dispatch Board', icon: GitBranch },
    { to: '/self-service', label: 'Self Service', icon: Smartphone },
    { to: '/profile', label: 'Profile', icon: UserCog },
  ],
  HR: [
    { to: '/', label: 'Dashboard', icon: LayoutDashboard },
    { to: '/employees', label: 'Employees', icon: Users },
    { to: '/users', label: 'Users', icon: UserCog },
    { to: '/requests', label: 'Requests', icon: FileText },
    { to: '/approvals', label: 'Approvals', icon: ShieldCheck },
    { to: '/groups', label: 'Dispatch Board', icon: GitBranch },
    { to: '/analytics', label: 'Analytics', icon: BarChart3 },
    { to: '/reports', label: 'Reports', icon: FileText },
    { to: '/holidays', label: 'Holidays', icon: CalendarDays },
    { to: '/audit-logs', label: 'Audit Logs', icon: ScrollText },
    { to: '/self-service', label: 'Self Service', icon: Smartphone },
    { to: '/profile', label: 'Profile', icon: UserCog },
  ],
  TRANSPORT_AUTHORITY: [
    { to: '/', label: 'Dashboard', icon: LayoutDashboard },
    { to: '/employees', label: 'Employees', icon: Users },
    { to: '/vehicles', label: 'Vehicles', icon: Car },
    { to: '/drivers', label: 'Drivers', icon: Bus },
    { to: '/driver-mobile', label: 'Driver Mobile', icon: Smartphone },
    { to: '/requests', label: 'Requests', icon: FileText },
    { to: '/approvals', label: 'Approvals', icon: ShieldCheck },
    { to: '/groups', label: 'Dispatch Board', icon: GitBranch },
    { to: '/grouping-templates', label: 'Grouping Templates', icon: GitBranch },
    { to: '/analytics', label: 'Analytics', icon: BarChart3 },
    { to: '/reports', label: 'Reports', icon: FileText },
    { to: '/holidays', label: 'Holidays', icon: CalendarDays },
    { to: '/self-service', label: 'Self Service', icon: Smartphone },
    { to: '/profile', label: 'Profile', icon: UserCog },
  ],
  PLANNING: [
    { to: '/', label: 'Dashboard', icon: LayoutDashboard },
    { to: '/groups', label: 'Dispatch Board', icon: GitBranch },
    { to: '/grouping-templates', label: 'Grouping Templates', icon: GitBranch },
    { to: '/analytics', label: 'Analytics', icon: BarChart3 },
    { to: '/reports', label: 'Reports', icon: FileText },
    { to: '/holidays', label: 'Holidays', icon: CalendarDays },
    { to: '/archive', label: 'Archive', icon: Archive },
    { to: '/audit-logs', label: 'Audit Logs', icon: ScrollText },
    { to: '/settings', label: 'Settings', icon: Settings },
    { to: '/profile', label: 'Profile', icon: UserCog },
  ],
  EMP: [
    { to: '/', label: 'Dashboard', icon: LayoutDashboard },
    { to: '/self-service', label: 'Self Service', icon: Smartphone },
    { to: '/profile', label: 'Profile', icon: UserCog },
  ],
};
